apiVersion: v1
kind: Service
metadata:
  name: kafka-proxy
  namespace: kafka-ca1
spec:
  ports:
  - name: kafka
    port: 9093
    targetPort: 8080
  selector:
    app: kafka-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-proxy
  namespace: kafka-ca1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-proxy
  template:
    metadata:
      labels:
        app: kafka-proxy
    spec:
      containers:
      - name: kafka-proxy
        image: rsmnarts/kowl:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKERS
          value: "kafka-0.kafka.kafka-ca1.svc.cluster.local:9092,kafka-1.kafka.kafka-ca1.svc.cluster.local:9092,kafka-2.kafka.kafka-ca1.svc.cluster.local:9092"
        - name: PROXY
          value: "true"
        - name: PROXY_LISTEN_ADDR
          value: "0.0.0.0:8080"
        - name: ALLOW_ALL
          value: "true"
