apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: n8n-secrets
  namespace: standard
  labels:
    app: n8n
    component: secrets
stringData:
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_USER: "n8n"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_PASSWORD: "mypassword"
  DB_POSTGRESDB_HOST: "n8n-postgres"
  DB_POSTGRESDB_PORT: "5432"
  # Basic auth credentials
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "n8n"
  N8N_BASIC_AUTH_PASSWORD: "mypassword"

  N8N_HOST: "demo.test"
  N8N_ENCRYPTION_KEY: "mypassword"
  GENERIC_TIMEZONE: "Europe/Lisbon"
  WEBHOOK_TUNNEL_URL: "http://demo.test/"
  NODE_ENV: "production"
  N8N_METRICS: "true"
  # Increase node max memory
  NODE_OPTIONS: "--max_old_space_size=1024"
  N8N_SECURE_COOKIE: "false"
  N8N_KAFKA_BROKER: kafka.kafka.svc.cluster.local:9092
  # Set n8n to work as single thread instead of forking to worker threads
  # EXECUTIONS_PROCESS: "main"
