---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
  namespace: standard
  labels: &labels
    app: n8n
    component: deployment
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels 
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5678"
        timestamp: "20230703123426"
        prometheus.io/path: /metrics
    spec:
      containers:
      - name: n8n
        image: lismgmk/lis-n8n:1.5.3
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-metrics
          containerPort: 5678
        env:
        - name: N8N_LOG_LEVEL
          value: 'debug'
        - name: N8N_LOG_OUTPUT
          value: 'console'
        - name: N8N_KAFKA_TRIGGER_LOG_LEVEL
          value: "debug"
        - name: N8N_KAFKA_BROKER
          value: "kafka.kafka-ca1.svc.cluster.local:9092"
        - name: N8N_KAFKA_TOPIC
          value: "test"
        - name: N8N_KAFKA_GROUP_ID
          value: "n8n"
        envFrom:
        - secretRef:
            name: n8n-secrets
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5678
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5678
        resources:
          limits:
            cpu: "1.0"
            memory: "1024Mi"
          requests:
            cpu: "0.5"
            memory: 512Mi
