apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  namespace: kafka-ca1
  labels:
    app: redpanda-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
        - name: redpanda-console
          image: redpandadata/console:v2.4.6
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-console-service
  namespace: kafka-ca1
  labels:
    app: redpanda-console
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # Вы можете выбрать любой доступный порт в диапазоне 30000-32767
  selector:
    app: redpanda-console
