apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka
data:
  kafka.properties: |
    broker.id=0
    log.dirs=/kafka-logs
    zookeeper.connect=zookeeper:2181
    listeners=PLAINTEXT://0.0.0.0:9092
    advertised.listeners=PLAINTEXT://kafka.kafka.svc.cluster.local:9092
