apiVersion: v1
kind: Namespace
metadata:
  name: kafka-ca1

---
apiVersion: v1
kind: Namespace
metadata:
  name: standard

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: v1
kind: Namespace
metadata:
  name: browserless

