apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserless
  namespace: browserless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browserless
  template:
    metadata:
      labels:
        app: browserless
    spec:
      containers:
        - name: browserless
          image: browserless/chrome:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '4024Mi'
              cpu: '1000m'
            limits:
              memory: '4024Mi'
              cpu: '2000m'
          env:
            - name: PREBOOT_CHROME
              value: 'true'
            - name: CONNECTION_TIMEOUT
              value: '60000'
            - name: MAX_CONCURRENT_SESSIONS
              value: '10'
---
apiVersion: v1
kind: Service
metadata:
  name: browserless-service
  namespace: browserless
spec:
  type: NodePort
  selector:
    app: browserless
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
