apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserless
  namespace: browserless
  labels: &labels
    app: browserless
    component: deployment
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels 
    spec:
      containers:
        - name: browserless
          image: browserless/chrome:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '4024Mi'
              cpu: '1000m'
            limits:
              memory: '4024Mi'
              cpu: '2000m'
          env:
            - name: PREBOOT_CHROME
              value: 'true'
            - name: CONNECTION_TIMEOUT
              value: '60000'
            - name: MAX_CONCURRENT_SESSIONS
              value: '10'

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: browserless-service
#   namespace: browserless
#   annotations:
#     prometheus.io/probe: "true"
#     prometheus.io/probe-path: "/healthz"
#   labels:
#     app: browserless
#     component: service
# spec:
#   type: ClusterIP
#   selector:
#     app: browserless
#     component: deployment
#   ports:
#   - protocol: TCP
#     name: http
#     port: 30000
#     targetPort: 3000
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: browserless-ingress
#   namespace: browserless
#   labels:
#     app: browserless
#     component: ingress
#   annotations:
#     nginx.ingress.kubernetes.io/add-base-url: 'true'
# spec:
#   rules:
#     - host: browserless.test
#       http:
#         paths:
#           - pathType: Prefix
#             path: /
#             backend:
#               service:
#                 name: browserless
#                 port:
#                   number: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: browserless-service
  namespace: browserless
spec:
  type: NodePort
  selector:
    app: browserless
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000